name: Fetch RSS Feed

on:
  schedule:
  #  - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:    # 允许手动触发

permissions:
  contents: write  # 赋予写权限

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CURL
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download RSS Content
        env:
          RSS_URL: ${{ secrets.RSS_URL }}
        run: |
          chmod +x fetch_rss.sh
          ./fetch_rss.sh

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          git commit -m "Update RSS feed at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${GITHUB_REF#refs/heads/}
